version: "3.8"
services:
  backend:
    image: "infozaid/springboot-react-fullstack:7.12.2024.7.53.59"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev