
services:
  backend:
    image: "infozaid/springboot-react-fullstack:29.11.2024.9.27.28"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://awseb-e-es32pmm6wf-stack-awsebrdsdatabase-xttthz98r7ub.c3il0a7cmawb.us-east-1.rds.amazonaws.com:5432/infozaid
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect